### ISSUE TITLE
Can't use number 8 inside a prepositional syntagm in French

### ISSUE THREAD

**Issue by jeremyk6** [lapalme/pyrealb#4]
Hello, I just figured out that this code fail :

```python
from pyrealb import *
loadFr()
n = 8
print(
    PP(
        P("de"),
        NO(n).dOpt({"nat": True})
    )
)
```

Expected output : "de huit". Error obtained :

```
Traceback (most recent call last):
  File "/Users/jeremy/Developpement/crossroadsdescriber/test.py", line 6, in <module>
    print(
  File "/opt/homebrew/lib/python3.10/site-packages/pyrealb/Constituent.py", line 653, in __str__
    return self.toSource(-1) if debug else self.realize()
  File "/opt/homebrew/lib/python3.10/site-packages/pyrealb/Constituent.py", line 642, in realize
    terminals=self.real()
  File "/opt/homebrew/lib/python3.10/site-packages/pyrealb/Phrase.py", line 974, in real
    return self.doFormat(res)
  File "/opt/homebrew/lib/python3.10/site-packages/pyrealb/Constituent.py", line 573, in doFormat
    self.doElisionFr(cList)
  File "/opt/homebrew/lib/python3.10/site-packages/pyrealb/Constituent.py", line 426, in doElisionFr
    if (elidableWordFrRE.match(w1) and isElidableFr(w2,cList[i+1].lemma,cList[i+1].constType) and w3NoWords):
  File "/opt/homebrew/lib/python3.10/site-packages/pyrealb/Constituent.py", line 404, in isElidableFr
    if pos not in lexiconInfo:pos=lexiconInfo.keys()[0] # try the first pos if current not found
TypeError: 'dict_keys' object is not subscriptable
```

It actually works for any n ("d'un", "de deux", etc.) except 8 or any number starting with 8 (8xx, 8xxxx).

**Comment by lapalme** [comment]
You are right, this is a bug for the élision of a French number written in letter starting with h.
It willl be corrected in the next version, soon.

Thanks for pointing this out.
